### ISSUE TITLE
Publishing has unexpected outcome

### ISSUE THREAD

**Issue by jorgeolivero** [dropbox/amqp-coffee#34] opened 2015-06-16 18:37 UTC
lib-version: 0.1.22rc4
lang: JS

I am publishing a message to user queues through a topic exchange named "inbox.events". 
The user queues are bound to the exchanges with routing keys following this scheme: "user.events.user_id.#". 

Here is my publishing code:

![screen shot 2015-06-16 at 2 27 43 pm](https://cloud.githubusercontent.com/assets/3119712/8190991/f240e4fa-1433-11e5-8a94-d7338bc3efed.png)

This is the console output:

![screen shot 2015-06-16 at 2 29 50 pm](https://cloud.githubusercontent.com/assets/3119712/8191057/400b3ca8-1434-11e5-90f9-f4181f42478e.png)

The problem is that although I am publishing to a different routing_key based on the current iteration of the users array, one user queue receives both messages. Are there any known issues with how published messages make their way out of the client lib and through to Rabbit?

Many thanks.

**Comment by barshow** [comment] 2015-06-17 06:24
I dont know any issues, my initial thought would be we're overwriting the outgoing routing key, but looking through the code I think we're protected from that.   Can you run you test script again with DEBUG=*  AMQP=3 that will print out all kinds of useful information.  Thank you

**Comment by barshow** [comment] 2015-06-17 06:30
actually run with AMQP=4

**Comment by jorgeolivero** [comment] 2015-06-17 15:59
@barshow So I wrote this script to isolate this interaction from the rest of my application, and recreate the issue.

The script creates a connection, creates a topic exchange, creates two queues and binds them to the exchange with unique routing keys, and then publishes to both queues. 

I ran the script with the the debug flags you mentioned and everything seemed normal. Unfortunately, both messages still ended up in one user's queue.

Please let me know if I'm overlooking something, because it seems that the lib is handling these publishes incorrectly.

```javascript
var AMQP = require('amqp-coffee');
var async = require('async');

var users = [{
    'user_id': '123'
}, {
    'user_id': '456'
}];

var getTestConnection = function (cb) {
    console.log('creating connection');
    var opts = {
    	'host': 'localhost'
    };
    var conn = new AMQP(opts, function (err, c) {
		if (err) throw err;
		cb(null, conn);
    });
};

var createTopicExchange = function (conn, done) {
    var name = 'inbox.events';
    if (typeof name != 'string') throw new Error('suppy topic exchange name');
    var opts = {
		'exchange': name,
		'type': 'topic',
		'passive': false,
		'durable': false
    };
    var declareExchange = function (opts, exchange, cb) {
		console.log('declaring exchange');
		exchange.declare(opts, function (err, res) {
	    	if (err) return cb(err);
	    	cb(null, exchange);
		});
    };
    var fns = [
		conn.exchange.bind(conn, opts),
		declareExchange.bind(null, opts)
    ];
    async.waterfall(fns, function (err, exchange) {
		if (err) throw err;
		done(null, conn);
    });
};

var createTwoQueuesAndBindToExchange = function (users, conn, done) {
    var queuePrefix = 'user.events';
    var createDeclareBind = function (u, cb) {
		var opts = {
		    'queue': [queuePrefix, u.user_id].join('.'),
		    'durable': false,
		    'passive': false
		};
		var fns = [
		    conn.queue.bind(conn, opts),
		    function declareQueue (queue, next) {
				console.log('declaring queue')
				queue.declare(opts, function (err, res) {
				    if (err) return next(err);
				    next(null, queue);
				});
		    },
		    function bindQueue (queue, next) {
				console.log('binding queue');
				var routing = [queuePrefix, u.user_id, '#'].join('.');
				var name = [queuePrefix, u.user_id ].join('.');
				queue.bind('inbox.events', routing, name, function (err) {
				    if (err) return next(err);
				    next(null, queue);
				});
		    }
		];
		async.waterfall(fns, cb);
    };
    async.map(users, createDeclareBind, function (err, queues) {
		if (err) throw err;
		done(null, conn);
    });
};

function sendEvents(users, conn, done) {
    var msg = {'test': 'msg'};
    msg = new Buffer(JSON.stringify(msg));
    var publishOpts = {
		'confirm': true,
		'contentType': 'application/json'
    };
    var Publish = function (user, cb) {
		var uid = user.user_id;
		var pattern = ['user.events', uid].join('.');
		console.log('publishING to pattern >', pattern);
		conn.publish('inbox.events', pattern, msg, publishOpts, function (err) {
		    if (err) return cb(err);
		    console.log('publishED to pattern >', pattern);
		    cb();
		});
    };
    async.map(users, Publish, function (err) {
		if (err) return done(err);
		console.log('publishing complete');
		done(null, conn);
    });
};

var fns = [
    getTestConnection,
    createTopicExchange,
    createTwoQueuesAndBindToExchange.bind(null, users),
    sendEvents.bind(null, users)
];

async.waterfall(fns, function (err, result) {
    if (err) throw err;
    console.log('script complete');
});
```

**Comment by barshow** [comment] 2015-06-17 21:06
Wow great find!  Thanks for taking the time and writing that test script.  I would consider this a bug and its fixed in https://github.com/dropbox/amqp-coffee/pull/35 or 0.1.22-rc5  The problem is the shared options object, didn't test for that and routing key was getting nested in it, and therefor clobbered in situations like this.  I added a test and fixed that.

**Comment by jorgeolivero** [comment] 2015-06-18 15:05
No problem, thanks for the quick turnaround.

**Closed** 2015-06-18 16:51 UTC
